name       : haskell-extra
version    : 1.6.20
release    : 3
source     :
    - https://hackage.haskell.org/package/extra-1.6.20/extra-1.6.20.tar.gz : 19ea4ed3caec0a7b7f53d1ce59854728bb902f19c3cff0f77d390ea6479da02f
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library of extra functions for the standard Haskell libraries.
description: |
    A library of extra functions for the standard Haskell libraries. Most functions are simple additions, filling out missing functionality. A few functions are available in later versions of GHC, but this package makes them available back to GHC 7.2.
builddeps  :
    - haskell-cabal-install
    - haskell-clock-devel
    - haskell-semigroups-devel
rundeps    :
    - devel:
        - haskell-clock-devel
        - haskell-semigroups-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
