name       : haskell-extra
version    : 1.5.1
release    : 1
source     :
    - http://hackage.haskell.org/package/extra-1.5.1/extra-1.5.1.tar.gz : 8f3397c7a176045f1bb3b2a181e36b54192cb6fb5e99a9d28552975130ec49fc
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library of extra functions for the standard Haskell libraries.
description: |
    A library of extra functions for the standard Haskell libraries. Most functions are simple additions, filling out missing functionality. A few functions are available in later versions of GHC, but this package makes them available back to GHC 7.2.
builddeps  :
    - haskell-cabal-install
    - haskell-clock
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register