name       : haskell-extra
version    : 1.6.6
release    : 2
source     :
    - https://hackage.haskell.org/package/extra-1.6.6/extra-1.6.6.tar.gz : 79996e6a8add465b9ae6253249199afc7fb2e4df475744dbe32b3c0b4573a09d
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library of extra functions for the standard Haskell libraries.
description: |
    A library of extra functions for the standard Haskell libraries. Most functions are simple additions, filling out missing functionality. A few functions are available in later versions of GHC, but this package makes them available back to GHC 7.2.
builddeps  :
    - haskell-cabal-install
    - haskell-clock
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |-
    %cabal_install
    %cabal_register
